# Generated by Django 2.2.12 on 2020-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='EMPLID', max_length=11, primary_key=True, serialize=False)),
                ('chinese_name', models.CharField(db_column='NAME', max_length=50)),
                ('english_name', models.CharField(db_column='NAME_A', max_length=50)),
                ('department_id', models.CharField(db_column='DEPTID', max_length=10)),
                ('department_name', models.CharField(db_column='DESCR', max_length=30)),
                ('job_title', models.CharField(db_column='DESCR60_A', max_length=60)),
                ('extension', models.CharField(db_column='PHONE_A', max_length=19)),
                ('mail', models.EmailField(db_column='EMAIL_ADDRESS_A', max_length=50)),
                ('supervisor_id', models.CharField(db_column='SUPERVISOR_ID', max_length=11)),
                ('site', models.CharField(db_column='SITE_ID_A', max_length=6)),
            ],
            options={
                'db_table': 'PS_EE_DQMS_VW_A',
                'ordering': ['employee_id'],
                'managed': False,
            },
        ),
    ]
