# Generated by Django 2.2.12 on 2020-04-29 01:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField()),
                ('project_id', models.PositiveIntegerField()),
                ('develop_team_function', models.CharField(max_length=20, verbose_name='the function of develop team')),
                ('develop_team_sub_function', models.CharField(max_length=20, verbose_name='the sub function of develop team')),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(verbose_name="order's current status")),
                ('initator', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assigner', django.contrib.postgres.fields.jsonb.JSONField(verbose_name="order's assigner (PO/PM)")),
                ('developers', django.contrib.postgres.fields.jsonb.JSONField(verbose_name="order's developer member and contact person")),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('form_begin_time', models.DateTimeField(auto_now_add=True)),
                ('form_end_time', models.DateTimeField(null=True)),
                ('expected_develop_duration_day', models.FloatField(verbose_name='the expected duration(day) of development')),
                ('actual_develop_duration_day', models.FloatField(verbose_name='the actual duration(day) of development')),
                ('repository_url', models.URLField(max_length=1000)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='signature.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
