# Generated by Django 2.2.13 on 2020-07-02 10:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.IntegerField(default=2, verbose_name="order's account"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.IntegerField(default=3, verbose_name="order's project"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name="order's current status"),
        ),
    ]
