# Generated by Django 2.2.27 on 2022-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_auto_20210428_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='system',
            field=models.IntegerField(null=True, verbose_name="order's system"),
        ),
        migrations.AddField(
            model_name='ordertracker',
            name='system',
            field=models.IntegerField(null=True, verbose_name="order's system"),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.IntegerField(null=True, verbose_name="order's account"),
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.IntegerField(null=True, verbose_name="order's project"),
        ),
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Return', 'Return'), ('Close', 'Close'), ('', '')], max_length=50),
        ),
    ]
